### ISSUE TITLE
Revise and harmonise nomenclature for spine segments

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/uberon#2884]
The nomenclature used for the spine is variable depending on the region:

<img src="https://github.com/obophenotype/uberon/assets/94959119/3d2f5697-e49d-4b22-9738-0e41737a9497" width=50% height=10%>

![image](https://github.com/obophenotype/uberon/assets/94959119/c0832940-ea23-4bb2-a479-62d561e2f4f2)
![image](https://github.com/obophenotype/uberon/assets/94959119/2d114909-8d9a-46b7-a7d3-ea7153c1142e)

- [ ] A consensus is needed to harmonise the nomenclature. First option is using the letter + number formula (eg C1, T3, L2, S5,... segment of X spinal cord). The second option is using ordinal numbers  (eg first lumbar spinal cord segment). I'm in favour of the first option as it is more standard, is more visual and keeps the segments in order.
- [ ] Segments lack definition, would a standard definition be sufficient (eg "The first segment of the cervical region in the spinal cord")?
- [ ] The current terms are a representation of the human spine. Should we leave it as it is or add more segments? (Some mammals have as many as 25 thoracic segments or more!)

**Comment by aleixpuigb** [comment]
FYI @emquardokus, the names have been changed and a definition has been added.
